### PR TITLE
Add Makefile and linter/formatter configuration

### LINKED ISSUE #30: Add Makefile and linter/formatter configuration
- [x] It would be cool to add same linting (flake8) / formatting (black) config in this package as in Masonite core repo.
- [x] Also adding a Makefile to run commands easily in development

@josephmancuso 
- [x] Should we use GitHub Actions for this repo to get tests reports and linting for open PR ?

### PR DESCRIPTION
**Pull request by girardinsamuel**
Fixes #30

### CODE REVIEW

**Comment by josephmancuso** [comment]
@girardinsamuel hmm this is strange. This repo looks a bit outdated

**Comment by josephmancuso** [comment]
I'm gonna spent an hour or two updating it today. Looks like its still using circle ci and not GitHub actions

**Review by josephmancuso — APPROVED** [review]

**Comment by josephmancuso** [comment]
merging to 3.0 branch

**Comment by girardinsamuel** [comment]
Yes, I should have worked from 3.0 for all PR maybe ?
Maybe we could also now that black is added, format code with black in one commit in another branch 💪

**Comment by josephmancuso** [comment]
Yes the 3.0 branch is what installs with Masonite 2.3

**Pull request merged**
