### PR TITLE
Fix standalone usage

### PR DESCRIPTION
**Pull request by girardinsamuel**
Fixes usage when used outside a masonite project:
This does not raise errors anymore.

It has been tested on this small snippet outside a Masonite project:
```python
from masonite.validation import Validator, required, exists, accepted

payload = {
    'user': 'username123',
    'company': '',
    'terms': 'on' # For checkboxes
}

errors = Validator().validate(
    payload,
    required(['user', 'company', 'terms']),
    accepted('terms')
  )

print(errors)
```

### CODE REVIEW

**Comment by girardinsamuel** [comment]
validator decorator not working anymore because, when removing Responsable inheritance :

```python
        # Masonite response.py file
        # ...
        if isinstance(view, tuple):
            view, status = view
            self.status(status)

        if not self.get_status_code():
            self.status(status)

        if isinstance(view, (dict, list)):
            return self.json(view, status=self.get_status_code())
        elif hasattr(view, "serialize"):
            return self.json(view.serialize(), status=self.get_status_code())
        elif isinstance(view, int):
            view = str(view)
        elif isinstance(view, Responsable): # <=== it can't use this anymore
            view = view.get_response()
        elif isinstance(view, self.request.__class__):
            view = self.data()
        elif view is None:
            raise ResponseError(
                "Responses cannot be of type: None. Did you return anything in your responsable method?"
            )

        if isinstance(view, str):
            self.content = bytes(view, "utf-8")
            self.app.bind("Response", bytes(view, "utf-8"))
        else:
            self.content = view
            self.app.bind("Response", view) # <=== so view e.g. MessageBag here is directly returned without being serialized..

        self.make_headers()

        return self.data()
```

**Comment by girardinsamuel** [comment]
In addition, to really remove masonite dependency from source (not from tests)
there is one import left in `Validator.py`
```python
from masonite.dot import Dot as DictDot
```
This utility class is implemented inside masonite, either we hard-code it in validation package or I don't know 👎

**Comment by josephmancuso** [comment]
So the Responsable is probably not even valid thing to do lol. What you can probably do instead of change this line of code:

https://github.com/MasoniteFramework/masonite/blob/383cf4607700bfa442fa6bbf33c764035eee2fee/src/masonite/response.py#L161-L162

to something like 

```python
elif isinstance(view, Responsable) or hasattr(view, 'get_response'):
            view = view.get_response()
```

Then we can just make sure this has the `get_response` method. I think I made this change in M4 lol

**Comment by girardinsamuel** [comment]
We should first release this PR https://github.com/MasoniteFramework/masonite/pull/433 in Masonite.
Then the tests should pass in this PR.

**Comment by girardinsamuel** [comment]
This package is now integrated into Masonite 4, so this PR is not needed anymore.

**Pull request closed without merging**
