### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by ar45**
- Fixed email validator to accept single letter username
- Fixed package namespace issue when installing masonite externally.

### CODE REVIEW

**Comment by girardinsamuel** [comment]
Hi @ar45, thanks for your contribution !

Could you add a unit test for checking e-mail validation rule with single letter username ? 

👍🏼

**Comment by girardinsamuel** [comment]
Hi @ar45, just add this test below `test_email` in `test_validation.py` and we will merge this PR
```python
def test_email_with_one_letter_username(self):
    validate = Validator().validate({"email": "u@example.com"}, email(["email"]))
    self.assertEqual(len(validate), 0)
```
Thanks !

**Comment by ar45** [comment]
@girardinsamuel Done Thanks

**Comment by girardinsamuel** [comment]
@josephmancuso PR ready !

**Review by josephmancuso — APPROVED** [review]

**Comment by josephmancuso** [comment]
@ar45 great thanks!

**Pull request merged**
